### ISSUE TITLE
Remove all start menu tiles

### ISSUE THREAD

**Issue by neolectron** [neolectron/clean-experience#1]
As seen on this picture, there's still Tiles in the start menu.
We should remove all Tiles and let the user decide if he wants to use it or not.

![image](https://user-images.githubusercontent.com/5268400/111029332-79990200-83fc-11eb-8efe-1c2b8fb2035c.png)

**Comment by MarvinGdt** [comment]
J'ai trouvé ces liens pour cette issue. J'ai repris le code et fait le script powershell direct à DL, ça fonctionne, j'ai testé chez moi ! 

Unpin les tiles : https://superuser.com/questions/1068382/how-to-remove-all-the-tiles-in-the-windows-10-start-menu/1310638#1310638

Script powershell : https://anonfiles.com/H2149219sc/unpin_all_ps1

**Comment by neolectron** [comment]
Tu gères,
je vais tester ça maintenant.

Si ta solution marche c'est le feu.

J'ai trouvé la version Registry only : 
https://winaero.com/default-start-menu-layout-windows-10/

**Comment by neolectron** [comment]
Ça marche c'est le feu
